version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://$S3_BUCKET --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'node_modules/**/*'
